### ISSUE TITLE
How to run in production mode?

### ISSUE THREAD

**Issue by afrianjunior** [petervmeijgaard/vue-2-boilerplate#34]
How to run in production mode?

**Comment by petervmeijgaard** [comment]
You can build the application with `npm run build`. The application will be build in the `dist`-directory. You can upload this directory to the root of your server and point the software where the index.html is located.

**Comment by petervmeijgaard** [comment]
Due to inactivity, I'm closing this issue

**Comment by encryptedtouhid** [comment]
I am working on a personal project with this vue application. When I build for production and host the files from "dist" to IIS. it shows White Blank Page. :/ very unexpected issue. @petervmeijgaard

**Comment by petervmeijgaard** [comment]
Hi @encryptedtouhid and thanks for your reply. I'll reopen this ticket, due to the fact that more people are experiencing problems with my setup.

I'm assuming you're running the app from a Windows Server-like environment? Can you provide more details about how you run the application? As in, what command do you run? What's the output of the command? Do you see any errors in the logs?

Also, keep in mind that this project is quite old and I haven't updated the repo for quite some time, so it could also be that various dependencies are outdated as well.

**Comment by petervmeijgaard** [comment]
Hi @encryptedtouhid, can you verify if the production build is still failing and provide me with a bit more information if it does?

**Comment by encryptedtouhid** [comment]
> Hi @encryptedtouhid and thanks for your reply. I'll reopen this ticket, due to the fact that more people are experiencing problems with my setup.
> 
> I'm assuming you're running the app from a Windows Server-like environment? Can you provide more details about how you run the application? As in, what command do you run? What's the output of the command? Do you see any errors in the logs?
> 
> Also, keep in mind that this project is quite old and I haven't updated the repo for quite some time, so it could also be that various dependencies are outdated as well.

hello @petervmeijgaard , Thank you for your kind reply & sorry for late response. I was busy with that issue and successfully fixed it.  It was just a issue with router.  but it not clear to me. 
I had to change meta tag "auth" & "guest" from true to false. after that it starting to show. 

![image](https://user-images.githubusercontent.com/10276184/85924032-67e4ee00-b8b1-11ea-9354-5cc84059e769.png)

**Comment by petervmeijgaard** [comment]
Hi @encryptedtouhid! Yeah, by setting the meta to `guest`, you're allowing everybody to visit the page. By setting it to `auth`, only users who are logged in are able to view this page. I hope that this will clarify your problem. If so, I'd like to close this issue if that's alright by you

**Comment by encryptedtouhid** [comment]
> Hi @encryptedtouhid! Yeah, by setting the meta to `guest`, you're allowing everybody to visit the page. By setting it to `auth`, only users who are logged in are able to view this page. I hope that this will clarify your problem. If so, I'd like to close this issue if that's alright by you

sure <3
