### ISSUE TITLE
Question about eventBus

### ISSUE THREAD

**Issue by paolog22** [petervmeijgaard/vue-2-boilerplate#46]
hi sir.. i have this trouble about component communication, What would be the best approach for this should i use a global EventBus or make an entry to store for the UI components ? 
thanks

**Comment by petervmeijgaard** [comment]
Hey, @paolog22! Thanks for your question!

I like to keep my components as "dumb" as possible. The only way I think they should receive data, is from using props. For letting know that something happened to the component, the best approach is to emit an event. Let's say we have an alert message something like this:
```vue
<template>
  <div class="alert">
    <button class="close" @click="close">
      &times;
    </button>
    <slot>{{ content }}</slot>
  </div>
</template>
<script>

// Alert.vue
export default {
  /**
   * The properties this alert component can use.
   */
  props: {
    /**
     * The content that's shown inside the alert message.
     */
    content: {
      type: String,
      required: false,
    },
  },

  /**
   * The methods that are available for this alert-component
   */
  methods: {
    /**
     * Method used to emit the close event.
     */
    close() {
      this.$emit('close');
    },
  },
};
</script>
```
So when we click the button, the `close`-method will be called and the `close`-event will be fired.
Then you can listen for this `close`-event in your `page` or `layout`:

```vue
<template>
  <v-alert v-for="alert in alertMessages" @close="removeAlert(alert)">
    {{ alert }}
  </v-alert>
</template>
<script>
import VAlert from '@/components/Alert.vue';

// Page.vue
export default {  
  /**
   * The data object for this page
   */
  data() {
    return {
      alertMessages: [
        'Foo',
        'Bar',
      ],
    };
  },

  /**
   * The methods that this pagecan use
   */
  methods: {
    /**
     * Used to remove an alert from the array of alert messages.
     */
    removeAlert(alert) {
      this.alertMessages = this.alertMessages.filter(item => item !== alert);
    }
  },

  /**
   * The components that are being used on this page
   */
  components: {
    VAlert,
  },
};
</script>
```
So on the page, we are listening for the `@close`-event and when the event has been fired, the `removeAlert`-method will be called. This will simply remove the alert from the array of alert messages.

Does this answer your question?

**Comment by paolog22** [comment]
thanks for the feedback,, that is exactly what i am looking for.. and one more thing sir.. about vuex should i store my state on localstorage so even i refresh the page state are still there ?

**Comment by petervmeijgaard** [comment]
Hmm, I haven't tried `localStorage` in combination with Vuex. I fetch all the data once the application has been fully loaded. Perhaps [this Vuex plugin](https://github.com/robinvdvleuten/vuex-persistedstate) will answer your question.

Keep in mind that this makes it harder to keep your application up-to-date:
Let's say you load the application and you fetch a post from the API:
```json
{
  "id": 1,
  "body": "FooBody",
  "title": "FooTitle",
}
```
You store the Vuex-store in the `localStorage` and close your window. In the meantime, someone changes the body property of the same post to:
```json
{
  "id": 1,
  "body": "BarBody",
  "title": "BarTitle",
}
```
Now when you open the application, the initial state will be recovered, so the post is still stored as:
```json
{
  "id": 1,
  "body": "FooBody",
  "title": "FooTitle",
}
```

I'm not sure if there's a way to prevent this, but keep this in mind when you are storing the state in `localStorage`.

**Comment by paolog22** [comment]
hmm.. thank you sir.. just wondering because when i logged in the state of authenticated became true but then when i refresh the page i become false. .  that is why maybe i thought there is other way to do it.

thanks for the feedback sir. i will share here what i could found. :)

**Comment by petervmeijgaard** [comment]
Ah you are correct! This is a bug in the boilerplate. I'll fix this right away 🤙

**Comment by petervmeijgaard** [comment]
It should be fixed now 😄 
As a matter of fact, I am storing the token in `localStorage` when the user is logged in as you can see [here](https://github.com/petervmeijgaard/vue-2-boilerplate/blob/master/src/store/modules/auth/mutations.js#L31).
Then I check on load if the `id_token` has been set in `localStorage`. The mutation can be found [here](https://github.com/petervmeijgaard/vue-2-boilerplate/blob/master/src/store/modules/auth/mutations.js#L19) and I call this mutation [here](https://github.com/petervmeijgaard/vue-2-boilerplate/blob/master/src/main.js#L53).

**Comment by paolog22** [comment]
thanks sir.. :)
