### ISSUE TITLE
help question

### ISSUE THREAD

**Issue by paolog22** [petervmeijgaard/vue-2-boilerplate#47]
hi sir.. is there any other way to use existing jquery with this boilerplate ? because i have this working UI with jquery and i want to use it and make the data with vuejs ..
thanks sir.

**Comment by paolog22** [comment]
this is done! :D hahah thanks sir,, you may close it.. for reference for other.. all your jquery code put in inside `$(document).ready( () => {
})`;

**Comment by petervmeijgaard** [comment]
Hi @paolog22!

It's cleaner to call the jQuery plugins inside the `mounted`-method instead of using `$(document).ready{ () => }`.
This way all the stuff is loaded when the application has been booted correctly.
