### ISSUE TITLE
Autoprefixer issue on standalone scss files

### ISSUE THREAD

**Issue by agarwalvinit** [petervmeijgaard/vue-2-boilerplate#48]
below is my app.scss which I am importing in bootstrap.js.
```
@import "color";
@import "variable";
@import "breakpoints";
@import "mixin";
@import "common";
@import "ComingSoon/comingsoon";
@import "Home/home";
@import "NavBar/navbar";
@import "StickyHeader/stickyheader";
@import "HowItWorks/howitworks";
@import 'ProjectCard/projectcard';
@import "ContactUsCard/contactuscard";
@import "ContactUs/contactus";
@import "PromotionalSection/promotionalsection";
@import "OurPartners/ourpartners";
@import 'Internal/loginandforgot';
@import 'Customer/customerlogin';
@import 'Footer/footer';
```

and below is my build/utils.js
```
  var postcssLoader = {
    loader: 'postcss-loader',
    options: {
      plugin: require('autoprefixer'),
      minimize: process.env.NODE_ENV === 'production',
      sourceMap: options.sourceMap
    }
  }

  function generateLoaders(loader, loaderOptions) {
    var loaders = [cssLoader, postcssLoader]
    if (loader) {
      loaders.push({
        loader: loader + '-loader',
        options: Object.assign({}, loaderOptions, {
          sourceMap: options.sourceMap
        })
      })
    }
    if (options.extract) {
      return ExtractTextPlugin.extract({
        use: loaders,
        fallback: 'vue-style-loader'
      })
    } else {
      return ['vue-style-loader'].concat(loaders)
    }
  }
```
It is unable to auto prefix the css. And my flex is breaking in almost all browsers(which uses vendor prefix).

**Comment by petervmeijgaard** [comment]
Hi @agarwalvinit,

I think that I fixed the problem in commit https://github.com/petervmeijgaard/vue-2-boilerplate/commit/29cf1b1d6ef78f4c8de2a5c70442ca8aadfe901a.
Could you please check if that's the case? You can checkout the `develop`-branch to see if it's working correctly.

**Comment by petervmeijgaard** [comment]
Hi @agarwalvinit,

Could you please provide more information about your issue and check if the issue has been resolved yet by updating to the latest version of this boilerplate?

**Comment by agarwalvinit** [comment]
@petervmeijgaard I am sorry was out of the town.

**Comment by petervmeijgaard** [comment]
Hi @agarwalvinit,

Can you check if the issue still exists? I'm using the latest verion of Vue CLI and the CLI is now responsible for building the application, so I believe that they are responsible for autoprefixing the CSS.

My apologies for the late response, but I wanted to wait for Vue CLI 3 to release in order to fix the issues. Otherwise I had to rewrite the application twice, which would take me a lot of time to do.

**Comment by agarwalvinit** [comment]
Ya, It's working now. Thanks 👍
