### ISSUE TITLE
How to apply url-loader for stylus urls?

### ISSUE THREAD

**Issue by vsorrokin** [petervmeijgaard/vue-2-boilerplate#51]
Your boilerplate is great! I have a question:

I wrote in src/assets/styles/app.styl this:

`.logo {background-image: url('/static/img/logo.png')}`

But seems like it is not affected with webpack url-loader - I expected hashed url in builded project, but it is not. Can you please give the example about how to correctly configure webpack to apply url-loader for urls inside .styl files? Thank you!

**Comment by vsorrokin** [comment]
Seems like I understood. I need to set '/../../../static/img/logo.png' URL

**Comment by petervmeijgaard** [comment]
Glad you figured this problem out on your own! You can also place the image in the assets directory and use `url('~@/assets/img/logo.png')` if I'm correct...

**Comment by petervmeijgaard** [comment]
For more information, see https://vue-loader.vuejs.org/en/configurations/asset-url.html

**Comment by petervmeijgaard** [comment]
For more information, see https://vue-loader.vuejs.org/en/configurations/asset-url.html
