### ISSUE TITLE
webpack4

### ISSUE THREAD

**Issue by plehnen** [petervmeijgaard/vue-2-boilerplate#58]
This is my favorite boilerplate for vue, and I've tested a lot.
Any chance that this will be maintained again and ported to support webpack4 and all the latest versions?

**Comment by petervmeijgaard** [comment]
Hi @plehnen and thanks for your issue!
I'm still maintaining the boilerplate but I'm currently waiting for Vue CLI 3 to be released.
For the latest version of the boilerplate, see the `upgrade-to-cli-3` branch.
The Vue service will take care of the building. However, I'm not sure if Webpack 4 is used.

Hopefully Vue CLI will be released soon :)

**Comment by petervmeijgaard** [comment]
The latest version of the boilerplate is using Vue CLI 3, which is based on the latest version of Webpack.
