### ISSUE TITLE
change path app to src in vueture-cli

### ISSUE THREAD

**Issue by mangcoding** [petervmeijgaard/vue-2-boilerplate#61]
Hy Pete, thanks to make awesome boilerplate. i want to ask something..
how to change the folder base in vueture-cli (https://github.com/vueture/vueture-cli). when i start to write :

`vueture make:layout Base`

the component built inside src/app folder instead of src folder like your boilerplate has. Thanks.
```
-src
  -app
    -layouts
      --Base.vue
  ...
  -layouts
    --Default.vue
```

**Comment by petervmeijgaard** [comment]
Hi @mangcoding,

Unfortunately I don't have enough time on my hands for continuing with Vueture. I still on planning a generator for Vue from which you can create components, pages, layouts and more, but right now, I don't have the time.

My apologies for the inconvenience.
